version: '3.9'

services:

  # ╭──────────────────────────────────────────────────────────╮
  # │                         DATABASE                         │
  # ╰──────────────────────────────────────────────────────────╯
  sandboxcom_mariadb:
    image: mariadb:10.6.13-focal
    platform: $PLATFORM
    container_name: "${MARIADB_CONTAINER_REF}"
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=$MARIADB_DATABASE_NAME
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    volumes:
      - com_db-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - sandboxcom


  # ╭──────────────────────────────────────────────────────────╮
  # │                     PHP + WORDPRESS                      │
  # ╰──────────────────────────────────────────────────────────╯
  sandboxcom_wordpress:
    depends_on:
      - sandboxcom_mariadb
    build:
      dockerfile: Dockerfile
      context: ./config/docker
    platform: $PLATFORM
    container_name: sandboxcom_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: "${MARIADB_CONTAINER_REF}:3306"
      WORDPRESS_DB_USER: $MARIADB_ROOT_USERNAME
      WORDPRESS_DB_PASSWORD: $MARIADB_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MARIADB_DATABASE_NAME
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_HOME', '$WP_HOME' );
          define('WP_SITEURL', '$WP_SITEURL' );
          define('WP_DEBUG_DISPLAY', '0' );
          define('WP_DEBUG_LOG', '1' );
          define('FS_METHOD', 'direct');
      XDEBUG_CONFIG: 
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - com_website-data:/var/www/html
      - ${PWD}/config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${PWD}/application/wp-content:/var/www/html/wp-content
    networks:
      - sandboxcom

  # ╭──────────────────────────────────────────────────────────╮
  # │                          NGINX                           │
  # │                     Developer & Live                     │
  # ╰──────────────────────────────────────────────────────────╯
  sandboxcom_webserver_dev:
    depends_on:
      - sandboxcom_mariadb
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['dev']
    container_name: sandboxcom_webserver_dev
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT}:80"
    volumes:
      - com_website-data:/var/www/html
      - ${PWD}/config/nginx/nginx-conf-dev:/etc/nginx/conf.d
      - ${PWD}/application/wp-content:/var/www/html/wp-content
    networks:
      sandboxcom:
        aliases:
          - localhost



  sandboxcom_webserver_live:
    depends_on:
      - sandboxcom_wordpress
    image: nginx:1.23.4-alpine
    platform: $PLATFORM
    profiles: ['live']
    container_name: sandboxcom_webserver_live
    restart: unless-stopped
    ports:
      - "2180:80"
      - "21443:443"
    volumes:
      - com_website-data:/var/www/html
      - ${PWD}/config/nginx/nginx-conf-live:/etc/nginx/conf.d
      - ${PWD}/application/wp-content:/var/www/html/wp-content
    networks:
      sandboxcom:
        aliases:
          - sandbox.londonparkour.com
          - localhost


volumes:
  com_website-data:
  com_db-data:

networks:
  sandboxcom:
    driver: bridge