#!/bin/bash

# ╭──────────────────────────────────────────────────────────╮
# │                     Export Database                      │
# ╰──────────────────────────────────────────────────────────╯

source ./config/githooks/pre-commit-scripts/export_database.sh
